name: Group 5 OBJ Import Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  obj-import-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Blender
        run: |
          sudo snap install blender --classic

      - name: Run OBJ Import Test Suite
        run: |
          blender --background --python tests/python/import_empty.py
          blender --background --python tests/python/import_large_scales.py
          blender --background --python tests/python/import_multi_valid.py
          blender --background --python tests/python/import_partially_valid.py
          blender --background --python tests/python/import_single_missing_mtl.py
          blender --background --python tests/python/import_single_valid.py
